-- CreateTable
CREATE TABLE `usuarios` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `contrasena` VARCHAR(191) NOT NULL,
    `rol` ENUM('ADMINISTRADOR', 'DIRECTOR_ADMINISTRATIVO', 'CONTADOR', 'CAJERO', 'DIRECCION_ACADEMICA', 'COORDINACION_ACADEMICA', 'SECRETARIA_DOCENTE', 'ORIENTADOR_ESCOLAR', 'MAESTRO', 'TUTOR', 'ESTUDIANTE', 'VISITANTE') NOT NULL DEFAULT 'VISITANTE',
    `activo` BOOLEAN NOT NULL DEFAULT true,
    `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `usuarios_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
